# https://gecgithub01.walmart.com/mobile-platform/github-app-monolith
enabled_features:
  - autolabeler
  - bot-pr-merge
  - semantic-pull-requests
  - stalebot
  - merge-queue
  - stale-branch-bot
merge_user: rajdgreat007
add_pr_label: allowRetry
