name: learn-github-actions
on: [push]
jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - run: npm install -g bats
      - run: bats -v
      - run: npm install -g react
      - run: npm install -g pdfjs
      - run: npm install -g next
      - run: npm install -g jquery
      - run: npm install -g jquery-ui
      - run: npm install -g vue
      - run: npm install -g graphql
      - run: npm install -g typescript
      - run: npm install -g react-query
      - run: npm install -g maven-ui
      - run: npm install -g bootstrap
      - run: npm install -g copy-to-clipboard
      - run: npm install -g debounce
      - run: npm install -g deepmerge
      - run: npm install -g fastify
      - run: npm install -g file-saver
      - run: npm install -g http-proxy-middleware
      - run: npm install -g jszip
      - run: npm install -g msw
      - run: npm install -g next-compose-plugins
      - run: npm install -g next-transpile-modules
      - run: npm install -g node-fetch
      - run: npm install -g pino
      - run: npm install -g react-charts
      - run: npm install -g react-dom
      - run: npm install -g react-pdf
      - run: npm install -g tslib
      - run: npm install -g upath
      - run: npm install -g yargs
      - run: npm install -g babel-jest
      - run: npm install -g babel-loader
      - run: npm install -g babel-plugin-transform-minify-gql-template-literals
      - run: npm install -g caniuse-lite
      - run: npm install -g chalk
      - run: npm install -g chokidar
      - run: npm install -g chrome-remote-interface
      - run: npm install -g eslint
      - run: npm install -g execa
      - run: npm install -g fastify-cors
      - run: npm install -g gatsby
      - run: npm install -g gh-pages
      - run: npm install -g jest
      - run: npm install -g jest-axe
      - run: npm install -g lighthouse
      - run: npm install -g lint-staged
      - run: npm install -g loadash
      - run: npm install -g prettier
      - run: npm install -g puppeteer
      - run: npm install -g rollup
      - run: npm install -g rxjs
      - run: npm install -g sass
      - run: npm install -g svgo
      - run: npm install -g testcafe
      - run: npm install -g yaml
      - run: npm install -g tmp
      - run: npm install -g stylelint
      - run: npm install -g pretty-bytes
      - run: npm install -g p-limit
      - run: npm install -g redux
      - run: npm install -g puppeteer
      - run: npm install -g @angular/material
